---
- name: List systemd service units
  command: systemctl list-unit-files
  changed_when: false
  ignore_errors: true
  register: res

- name: Test if the service exists
  assert:
    that:
      - |
        {{ res.stdout_lines |
           select('regex', "^%s\s+.+$" % ssc_service) |
           list | length > 0 }}
    fail_msg: |
      {{ res | to_nice_json }}

# vim:sw=2:ts=2:et:
